COMMENT = 		Python library to sanitize/validate a string
MODPY_EGG_VERSION = 	3.2.0
PKGNAME =		py-${DISTNAME}

# MIT
HOMEPAGE = 		https://github.com/thombashi/pathvalidate
MAINTAINER = 		Anjeel <email@mail.com>
PERMIT_PACKAGE = 	Yes

CATEGORIES= 		devel
MODULES=		lang/python

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

FLAVOR =		python3
FLAVORS =		python3

DISTNAME= 		pathvalidate-${MODPY_EGG_VERSION}

.include	<bsd.port.mk>
