COMMENT = 		Pick an option in the terminal with a simple GUI
MODPY_EGG_VERSION = 	1.6.0
PKGNAME =		py-${DISTNAME}
CATEGORIES= 		devel

HOMEPAGE = 		https://github.com/aisk/pick
MAINTAINER = 		Anjeel <emaill@mail.com>
PERMIT_PACKAGE = 	Yes
# MIT

BUILD_DEPENDS =		devel/py-poetry-core
MODULES=		lang/python
MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools


FLAVOR =		python3
FLAVORS =		python3

DISTNAME= 		pick-${MODPY_EGG_VERSION}

.include	<bsd.port.mk>
